resolver: nightly-2017-12-13

packages:
- .

extra-deps:
- not-gloss-0.7.7.0
- spatial-math-0.4.0.0
# - OptDir-0.0.3
# - data-interval-1.3.0
# - extended-reals-0.2.2.0
# - finite-field-0.9.0
# - pseudo-boolean-0.1.6.0
# - queue-0.1.2
# - sign-0.4.3
